# Generated by Django 3.1.7 on 2021-02-24 14:41

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=50, validators=[common.validators.check_password], verbose_name='Password')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user', verbose_name='Image')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('gender', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], max_length=1, null=True, verbose_name='Gender')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('website', models.CharField(blank=True, max_length=150, validators=[common.validators.check_website], verbose_name='Website')),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[common.validators.check_phone_number], verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
    ]
