# Generated by Django 3.1.7 on 2021-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='_user_follow_+', to='user.User', verbose_name='follow'),
        ),
    ]
