# Generated by Django 3.1.7 on 2021-02-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210224_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(to='user.User', verbose_name='follow'),
        ),
    ]
