# Generated by Django 3.1.7 on 2021-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210224_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, to='user.User', verbose_name='follow'),
        ),
    ]
