# Generated by Django 3.1.7 on 2021-02-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210224_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_follow_+', to='user.User', verbose_name='follow'),
        ),
    ]
