# Generated by Django 3.1.7 on 2021-02-24 17:23

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210224_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[common.validators.check_password], verbose_name='Password'),
        ),
    ]
