# Generated by Django 3.1.7 on 2021-02-24 17:39

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210224_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, populate_from=['user_name'], unique=True),
        ),
    ]
