# Generated by Django 3.1.7 on 2021-02-25 11:23

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, unique=True, validators=[common.validators.check_user_name], verbose_name='Username'),
        ),
    ]
