# Generated by Django 3.1.7 on 2021-02-26 13:36

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210226_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[common.validators.check_phone_number], verbose_name='Phone number'),
        ),
    ]
