# Generated by Django 3.1.7 on 2021-02-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210226_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user/default_profile.png', null=True, upload_to='user', verbose_name='Image'),
        ),
    ]
