# Generated by Django 3.1.7 on 2021-02-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0011_user_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('localtion', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('image', models.ImageField(blank=True, upload_to='posts', verbose_name='Image')),
                ('content', models.TextField(verbose_name='Content')),
                ('comments', models.ManyToManyField(related_name='comments_set', through='post.Comment', to='user.User')),
                ('like', models.ManyToManyField(related_name='like_set', to='user.User', verbose_name='Like')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
