# Generated by Django 3.1.7 on 2021-03-17 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20210311_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='comments_set', through='post.Comment', to=settings.AUTH_USER_MODEL, verbose_name='comment'),
        ),
    ]
