# Generated by Django 3.1.7 on 2021-02-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210224_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='localtion',
            new_name='location',
        ),
    ]
