# Generated by Django 3.1.7 on 2021-03-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20210302_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_date']},
        ),
    ]
